version: '2'
services:
  fluentd:
    container_name: fluentd
    image: fluentd-test/fluentd
    build: ./fluentd
    volumes:
      - data:/fluentd/log
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    # logging:
    #   driver: "json-file"
      
  hellowinston:
    container_name: hellowinston
    image: fluentd-test/hello-winston
    build: ./hello-winston
    ports:
      - "4444:4000"
    # links:
    #   - fluentd 
    logging:
      driver: fluentd
      options: 
        tag: "{{.Name}}"
        # fluent-address: "localhost:24224"
        fluentd-async-connect: "true"
        # fluentd-retry-wait: "1s"
        # fluentd-max-retries: "30"
volumes:
  data:
    driver: local
