version: '2'
services:
  fluentd:
    container_name: fluentd
    image: fluentd-test/fluentd
    build: ./fluentd
    volumes:
      - data:/fluentd/log
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - fluentd_test
    links:
      - "elasticsearch"
    # logging:
    #   driver: "json-file"

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.6.0
    expose:
      - 9200
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
    networks:
      - fluentd_test

  kibana:
    container_name: kibana
    image: kibana:7.6.0
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"
    networks:
      - fluentd_test
          
  hellowinston:
    container_name: hellowinston
    image: fluentd-test/hello-winston
    build: ./hello-winston
    ports:
      - "4444:4000"
    networks:
      - fluentd_test
    # links:
    #   - fluentd 
    logging:
      driver: fluentd
      options: 
        tag: "{{.Name}}"
        fluentd-async-connect: "true"

volumes:
  data:
    driver: local

networks: 
  fluentd_test:
    external: true
